BbWeb/Areas/Admin/Controllers/CategoryController.cs
using BbWeb.Data;
using BbWeb.Interfaces.Manager;
using BbWeb.Models;
using BbWeb.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BbWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class CategoryController : Controller
    {
        // private readonly ApplicationDbContext _db;
        ICategoryManager _categoryManager;
        //public CategoryController(ApplicationDbContext db,ICategoryManager categoryManager)
        //{
        //    _db = db;
        //    _categoryManager = categoryManager;
        //}
        public CategoryController(ICategoryManager categoryManager)
        {
            _categoryManager = categoryManager;
        }
        public IActionResult Index()
        {
            // var post = _db.Categories.ToList();
            var post = _categoryManager.GetAll().ToList();
            return View(post);
        }

        // category create

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Category category)
        {
            if (ModelState.IsValid)
            {
                //_db.Categories.Add(category);
                //_db.SaveChanges();
               bool isSaved = _categoryManager.Add(category);
                if (isSaved)
                {
                    return RedirectToAction(nameof(Index));
                }
               
               
            }
            return View(category);
        }

        // category edit

        public IActionResult Edit(int? id)
        {
            if(id == null)
            {
                return NotFound();
            }

            // var post = _db.Categories.FirstOrDefault(c => c.Id == id);
            var post = _categoryManager.GetFirstOrDefault(c => c.Id == id);
            if(post == null)
            {
                return NotFound();
            }

            return View("Create",post);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Category category)
        {
            if (ModelState.IsValid)
            {
                // _db.Categories.Update(category);
             bool isSaved = _categoryManager.Update(category);
                if (isSaved)
                {
                    return RedirectToAction(nameof(Index));
                }
                
               
            }

            return View(category);
        }

        // Category delete

        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            //  var post = _db.Categories.FirstOrDefault(c => c.Id == id);
            var post = _categoryManager.GetFirstOrDefault(c => c.Id == id);
            if (post != null)
            {
                // _db.Categories.Remove(post);
               bool isSaved =_categoryManager.Delete(post);
                if (isSaved)
                {
                    return RedirectToAction(nameof(Index));
                }
                
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

BbWeb/Areas/Admin/Controllers/CompanyController.cs
using BbWeb.Data;
using BbWeb.Models;
using BbWeb.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BbWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class CompanyController : Controller
    {
        private readonly ApplicationDbContext _db;
        public CompanyController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            var posts = _db.Companies.ToList();
            return View(posts);
        }

        // Create company

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Company company)
        {
            if (ModelState.IsValid)
            {
                _db.Companies.Add(company);
                _db.SaveChanges();
                return RedirectToAction(nameof(Index));
            }

            return View(company);
        }


        // company edit
       

        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var post = _db.Companies.FirstOrDefault(c => c.Id == id);
            if(post == null)
            {
                return NotFound();
            }
            return View("Create", post);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Company company)
        {

      
            if (ModelState.IsValid)
            {
                _db.Companies.Update(company);
                _db.SaveChanges();
                return RedirectToAction(nameof(Index));
            }

            return View(company);
        }

        // delete post

        public IActionResult Delete(int? id)
        {
            if(id == null)
            {
                return NotFound();
            }

            var post = _db.Companies.FirstOrDefault(c => c.Id == id);
            if(post == null)
            {
                return NotFound();
            }

            _db.Companies.Remove(post);
            _db.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
    }
}

BbWeb/Areas/Admin/Controllers/DashboardController.cs
using BbWeb.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BbWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]

    public class DashboardController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

BbWeb/Areas/Admin/Controllers/ProductController.cs
using BbWeb.Data;
using BbWeb.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc.Rendering;
using BbWeb.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.EntityFrameworkCore;

namespace BbWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class ProductController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly IWebHostEnvironment _he;
        public ProductController(ApplicationDbContext db,IWebHostEnvironment he)
        {
            _db = db;
            _he = he;
        }
        public IActionResult Index(int pg=1,string SearchText = "")
        {
            List<Product> posts;
            SearchText = SearchText.ToLower();
            if(SearchText != "" && SearchText != null)
            {
                posts = _db.Products.Include(c => c.Category).Include(x => x.Tag).
                    Where(c => c.ProductName.ToLower().Contains(SearchText) || c.Description.ToLower().Contains(SearchText) ||
                    c.Category.CategoryName.ToLower().Contains(SearchText) || c.Tag.TagName.ToLower().Contains(SearchText)).ToList();
            }
            else
            posts = _db.Products.Include(c=>c.Category).Include(x=>x.Tag).ToList();

            //const int pageSize = 10;
            //if (pg < 1)
            //    pg = 1;

            //int recsCount = posts.Count();
            //var pager = new Pager(recsCount, pg, pageSize);
            //int recSkip = (pg - 1) * pageSize;
            //var data = posts.Skip(recSkip).Take(pager.PageSize).ToList();
            //this.ViewBag.Pager = pager; 
            return View(posts);
        }


        // create products

        public IActionResult Create()
        {
            ViewData["categoryId"] = new SelectList(_db.Categories.ToList(),"Id","CategoryName");
            ViewData["tagId"] = new SelectList(_db.Tags.ToList(), "Id", "TagName");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Product product,IFormFile image)
        {
            if (ModelState.IsValid)
            {
                // check same name  product already fexist or not

                //var searchProduct = _db.Products.FirstOrDefault(c => c.ProductName == product.ProductName);
                //if(searchProduct != null)
                //{
                //    ViewBag.message = "This product is already exist";
                //    ViewData["categoryId"] = new SelectList(_db.Categories.ToList(), "Id", "CategoryName");
                //    ViewData["tagId"] = new SelectList(_db.Tags.ToList(), "Id", "TagName");
                //    return View(product);
                //}

                // if same name product not exist
                // upload image when insert file

                if (image != null)
                {
                    var name = Path.Combine(_he.WebRootPath + "/Images", Path.GetFileName(image.FileName));
                    await image.CopyToAsync(new FileStream(name, FileMode.Create));
                    product.Image = "Images/" + image.FileName;
                }
                if (image == null)
                {
                    product.Image = "Images/default.png";
                }

                _db.Products.Add(product);
                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));


            }
            return View(product);
        }

        // product edit

        public IActionResult Edit(int? id)
        {
            ViewData["categoryId"] = new SelectList(_db.Categories.ToList(), "Id", "CategoryName");
            ViewData["tagId"] = new SelectList(_db.Tags.ToList(), "Id", "TagName");
            if (id == null)
            {
                return NotFound();
            }
            var product = _db.Products.Include(f=>f.Category).Include(c=>c.Tag).FirstOrDefault(c => c.Id == id);
            if (product == null)
            {
                return NotFound();
            }
            return View(product);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Product product, IFormFile image)
        {
            if (ModelState.IsValid)
            {

                if (image != null)
                {
                    var name = Path.Combine(_he.WebRootPath + "/Images", Path.GetFileName(image.FileName));
                    await image.CopyToAsync(new FileStream(name, FileMode.Create));
                    product.Image = "Images/" + image.FileName;
                }
                if (image == null)
                {
                    product.Image = "Images/default.png";
                }

                _db.Products.Update(product);
                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));


            }
            return View(product);
        }

        // product details

        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var result = _db.Products.Include(c => c.Category).Include(c => c.Tag).FirstOrDefault(c => c.Id == id);
            if (result == null)
            {
                return NotFound();
            }
            return View(result);

        }

        // product delete

        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var post = _db.Products.FirstOrDefault(c => c.Id == id);
            if (post == null)
            {
                return NotFound();
            }
            _db.Products.Remove(post);
            _db.SaveChanges();
            return RedirectToAction(nameof(Index));
        }


    }
}

BbWeb/Areas/Admin/Controllers/TagController.cs
using BbWeb.Data;
using BbWeb.Models;
using BbWeb.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BbWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class TagController : Controller
    {
        private readonly ApplicationDbContext _db;

        public TagController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            var tag = _db.Tags.ToList();
            return View(tag);
        }

        // Create tag

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Tag tag)
        {
            if (ModelState.IsValid)
            {
                _db.Tags.Add(tag);
                _db.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return View(tag);
        }

        // Tag update
        public IActionResult Edit(int? id)
        {
            if(id == null)
            {
                return NotFound();
            }
            var tag = _db.Tags.FirstOrDefault(c => c.Id == id);
            if(tag == null)
            {
                return NotFound();
            }

            return View("Create", tag);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Tag tag)
        {
            if (ModelState.IsValid)
            {
                _db.Tags.Update(tag);
                _db.SaveChanges();
                return RedirectToAction(nameof(Index));
            }

            return View(tag);
        }


        // Delete tag
        public IActionResult Delete(int? id)
        {

            if (id == null)
            {
                return NotFound();
            }
            var tag = _db.Tags.FirstOrDefault(c => c.Id == id);
            if (tag == null)
            {
                return NotFound();
            }
            _db.Tags.Remove(tag);
            _db.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
    }
}

BbWeb/Areas/Admin/Views/Dashboard/Index.cshtml
@using BbWeb.Utility

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" />
      <link rel="stylesheet" href="~/css/styles.css" asp-append-version="true" />
    <title>Bootstap 5 Responsive Admin Dashboard</title>
</head>

<body>
    <div class="d-flex" id="wrapper">
        <!-- Sidebar -->
        <div class="bg-white" id="sidebar-wrapper">
            <div class="sidebar-heading text-center py-4 primary-text fs-4 fw-bold text-uppercase border-bottom"><i
                    class="fas fa-user-secret me-2"></i>Codersbite</div>
            <div class="list-group list-group-flush my-3">
                <a href="#" class="list-group-item list-group-item-action bg-transparent second-text active"><i
                        class="fas fa-tachometer-alt me-2"></i>Dashboard</a>

                @if (User.IsInRole(SD.Role_Admin))
                {
                           <a asp-area="Admin" asp-controller="Category" asp-action="Index"
                 class="list-group-item list-group-item-action bg-transparent second-text fw-bold">Category</a>

                 
                <a asp-area="Admin" asp-controller="Tag" asp-action="Index"
                 class="list-group-item list-group-item-action bg-transparent second-text fw-bold">Tag</a>

                     
                <a asp-area="Admin" asp-controller="Product" asp-action="Index"
                 class="list-group-item list-group-item-action bg-transparent second-text fw-bold">Product</a>

                <a asp-area="Admin" asp-controller="Company" asp-action="Index"
                 class="list-group-item list-group-item-action bg-transparent second-text fw-bold">Company</a>
                }

         

                <a href="#" class="list-group-item list-group-item-action bg-transparent second-text fw-bold"><i
                        class="fas fa-project-diagram me-2"></i>Projects</a>
                <a href="#" class="list-group-item list-group-item-action bg-transparent second-text fw-bold"><i
                        class="fas fa-chart-line me-2"></i>Analytics</a>
                <a href="#" class="list-group-item list-group-item-action bg-transparent second-text fw-bold"><i
                        class="fas fa-paperclip me-2"></i>Reports</a>
                <a href="#" class="list-group-item list-group-item-action bg-transparent second-text fw-bold"><i
                        class="fas fa-shopping-cart me-2"></i>Store Mng</a>
                <a href="#" class="list-group-item list-group-item-action bg-transparent second-text fw-bold"><i
                        class="fas fa-gift me-2"></i>Products</a>
                <a href="#" class="list-group-item list-group-item-action bg-transparent second-text fw-bold"><i
                        class="fas fa-comment-dots me-2"></i>Chat</a>
                <a href="#" class="list-group-item list-group-item-action bg-transparent second-text fw-bold"><i
                        class="fas fa-map-marker-alt me-2"></i>Outlet</a>
                <a href="#" class="list-group-item list-group-item-action bg-transparent text-danger fw-bold"><i
                        class="fas fa-power-off me-2"></i>Logout</a>
            </div>
        </div>
        <!-- /#sidebar-wrapper -->

        <!-- Page Content -->
        <div id="page-content-wrapper">
            <nav class="navbar navbar-expand-lg navbar-light bg-transparent py-4 px-4">
                <div class="d-flex align-items-center">
                    <i class="fas fa-align-left primary-text fs-4 me-3" id="menu-toggle"></i>
                    <h2 class="fs-2 m-0">Dashboard</h2>
                </div>

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle second-text fw-bold" href="#" id="navbarDropdown"
                                role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                <i class="fas fa-user me-2"></i>John Doe
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="#">Profile</a></li>
                                <li><a class="dropdown-item" href="#">Settings</a></li>
                                <li><a class="dropdown-item" href="#">Logout</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </nav>

            <div class="container-fluid px-4">
                <div class="row g-3 my-2">
                    <div class="col-md-3">
                        <div class="p-3 bg-white shadow-sm d-flex justify-content-around align-items-center rounded">
                            <div>
                                <h3 class="fs-2">720</h3>
                                <p class="fs-5">Products</p>
                            </div>
                            <i class="fas fa-gift fs-1 primary-text border rounded-full secondary-bg p-3"></i>
                        </div>
                    </div>

                    <div class="col-md-3">
                        <div class="p-3 bg-white shadow-sm d-flex justify-content-around align-items-center rounded">
                            <div>
                                <h3 class="fs-2">4920</h3>
                                <p class="fs-5">Sales</p>
                            </div>
                            <i
                                class="fas fa-hand-holding-usd fs-1 primary-text border rounded-full secondary-bg p-3"></i>
                        </div>
                    </div>

                    <div class="col-md-3">
                        <div class="p-3 bg-white shadow-sm d-flex justify-content-around align-items-center rounded">
                            <div>
                                <h3 class="fs-2">3899</h3>
                                <p class="fs-5">Delivery</p>
                            </div>
                            <i class="fas fa-truck fs-1 primary-text border rounded-full secondary-bg p-3"></i>
                        </div>
                    </div>

                    <div class="col-md-3">
                        <div class="p-3 bg-white shadow-sm d-flex justify-content-around align-items-center rounded">
                            <div>
                                <h3 class="fs-2">%25</h3>
                                <p class="fs-5">Increase</p>
                            </div>
                            <i class="fas fa-chart-line fs-1 primary-text border rounded-full secondary-bg p-3"></i>
                        </div>
                    </div>
                </div>

                <div class="row my-5">
                    <h3 class="fs-4 mb-3">Recent Orders</h3>
                    <div class="col">
                        <table class="table bg-white rounded shadow-sm  table-hover">
                            <thead>
                                <tr>
                                    <th scope="col" width="50">#</th>
                                    <th scope="col">Product</th>
                                    <th scope="col">Customer</th>
                                    <th scope="col">Price</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <th scope="row">1</th>
                                    <td>Television</td>
                                    <td>Jonny</td>
                                    <td>$1200</td>
                                </tr>
                                <tr>
                                    <th scope="row">2</th>
                                    <td>Laptop</td>
                                    <td>Kenny</td>
                                    <td>$750</td>
                                </tr>
                                <tr>
                                    <th scope="row">3</th>
                                    <td>Cell Phone</td>
                                    <td>Jenny</td>
                                    <td>$600</td>
                                </tr>
                                <tr>
                                    <th scope="row">4</th>
                                    <td>Fridge</td>
                                    <td>Killy</td>
                                    <td>$300</td>
                                </tr>
                                <tr>
                                    <th scope="row">5</th>
                                    <td>Books</td>
                                    <td>Filly</td>
                                    <td>$120</td>
                                </tr>
                                <tr>
                                    <th scope="row">6</th>
                                    <td>Gold</td>
                                    <td>Bumbo</td>
                                    <td>$1800</td>
                                </tr>
                                <tr>
                                    <th scope="row">7</th>
                                    <td>Pen</td>
                                    <td>Bilbo</td>
                                    <td>$75</td>
                                </tr>
                                <tr>
                                    <th scope="row">8</th>
                                    <td>Notebook</td>
                                    <td>Frodo</td>
                                    <td>$36</td>
                                </tr>
                                <tr>
                                    <th scope="row">9</th>
                                    <td>Dress</td>
                                    <td>Kimo</td>
                                    <td>$255</td>
                                </tr>
                                <tr>
                                    <th scope="row">10</th>
                                    <td>Paint</td>
                                    <td>Zico</td>
                                    <td>$434</td>
                                </tr>
                                <tr>
                                    <th scope="row">11</th>
                                    <td>Carpet</td>
                                    <td>Jeco</td>
                                    <td>$1236</td>
                                </tr>
                                <tr>
                                    <th scope="row">12</th>
                                    <td>Food</td>
                                    <td>Haso</td>
                                    <td>$422</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>

            </div>
        </div>
    </div>
    <!-- /#page-content-wrapper -->
    

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js"></script>
    <script>
        var el = document.getElementById("wrapper");
        var toggleButton = document.getElementById("menu-toggle");

        toggleButton.onclick = function () {
            el.classList.toggle("toggled");
        };
    </script>
</body>

</html>